config/routes.rb
Rails.application.routes.draw do
  resources :audit_logs, except: [:new, :edit, :destroy] do
    member do
      get :confirm
    end
  end
  
  namespace :admin do
     resources :users
	   resources :posts
	   resources :admin_users

     root to: "users#index"
  end

  resources :posts do
    member do 
      get :approve
    end
  end
  devise_for :users, skip: [:registrations] # This remove the ability for users to register an account.
  root to: 'static#homepage'
end

app/views/shared/_alerts.html.erb
<% if flash[:alert] %>
  <%= js add_gritter(flash[:alert], title: "TimeTracker App Alert", sticky: false, image: :warning) %>
<% elsif flash[:error] %>
  <%= js add_gritter(flash[:error], title: "TimeTracker App Error", sticky: false, image: :error) %>
<% else %>
  <%= js add_gritter(flash[:notice], title: "TimeTracker App  Notification", sticky: false, image: :notice)  %>
<% end %>    

app/views/shared/_audit_log_tab.html.erb
<li class="<%= active?(audit_logs_path)%>">
	<%= link_to "Audit Log", audit_logs_path %>
</li>

app/views/shared/_nav.html.erb
<div class="logo">
	<h1>TimeTracker</h1>
</div>
<!-- TODO -->
<% if current_user %>
	<ul class="custom-nav nav nav-tabs">
		<li class="<%= active?(root_path) %>">
		<%= link_to "Home", root_path %>
		</li>
		<li class="<%= active?(posts_path)%>">
		<%= link_to "Time Entries", posts_path %>
		</li>
		<!-- TODO:: possibly refactor -->
		<%= render 'shared/audit_log_tab'if policy(AuditLog).index? %>

		<li class="<%= active?(new_post_path)%>">
		<%= link_to "Request Overtime", new_post_path, id: 'new_post_from_nav' %>
		</li>
		<li class="dropdown pull-right">
			 <a href="#" data-toggle="dropdown" class="dropdown-toggle">Options<strong class="caret"></strong></a>
			<ul class="dropdown-menu">

				<!-- TODO -->
				<% if current_user.try(:type) == 'AdminUser' %>
					<li>
					  <%= link_to "Admin Dashboard", admin_root_path %>
					</li>
					<li class="divider"></li>
				<% end %>
				<!-- TODO -->

				<li>
				  <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
				</li>
			</ul>
		</li>
	</ul>
<% end %>
<!-- TODO -->